from flask_restx import Namespace, Resource, fields
from flask import request
from app import db
from app.models.item import Item
from datetime import datetime #to enfore the daily limits

from app.models.user import User
#only needed for the foreign key relationship, but we will need it to check if the owner exists in the database. 
#if we implement user authentication, we will not need to check if the owner exists, since it will be derived from the authenticated user's information.

item_ns = Namespace("items", description="Item operations")

item_model = item_ns.model("Item", {
    "title": fields.String(required=True, example="Potato"),
    "description": fields.String(required=True, example="A fine peruvian potato"),
    "category": fields.String(required=True, example="Food"),
    "price": fields.Float(required=True, example=19.99),
    "owner": fields.String(required=True, example="test123")  # This will be the username of the owner, which is a foreign key to the User model.
})
item_model_with_id = item_ns.model("Item", {
    "id": fields.Float(required=True),
    "title": fields.String(required=True, example="Potato"),
    "description": fields.String(required=True, example="A fine peruvian potato"),
    "category": fields.String(required=True, example="Food"),
    "price": fields.Float(required=True, example=19.99),
    "owner": fields.String(required=True, example="test123")  # This will be the username of the owner, which is a foreign key to the User model.
})
#Note for team:
#Once we implement user authentication, we will not require the owner field to be provided by the user, as it will be derived from the authenticated user's information.

@item_ns.route("/")
class ItemList(Resource):

    @item_ns.expect(item_model)
    @item_ns.response(201, "Item created successfully")
    @item_ns.response(400, "Validation error")
    def post(self):

        data = item_ns.payload
        ...

        title = (data.get("title") or "").strip()
        description = (data.get("description") or "").strip()
        category = (data.get("category") or "").strip().lower()
        owner = (data.get("owner") or "").strip()
        price = data.get("price")
        
        try: #to ensure that the price is a valid float, we will attempt to convert it to a float. If it fails, we will return a 400 error with a message indicating that the price must be a valid number.
            price = float(price)
        except (TypeError, ValueError):
            item_ns.abort(400, "Price must be a valid number")
                

        if not all([title, description, category, owner]) or price is None:
            item_ns.abort(400, "All fields are required")
        if price is None:
            item_ns.abort(400, "Price is required")

        if price < 0:
            item_ns.abort(400, "Price must be non-negative")

        # Check if the owner exists in the database, only needed util we get authentication          
        if not User.query.filter_by(username=owner).first():
            item_ns.abort(400, "Owner does not exist")

        # Enforce daily limit of 2 items per user
        today = datetime.utcnow().date()

        count = Item.query.filter(
            Item.owner == owner,
            db.func.date(Item.created_at) == today
        ).count()

        if count >= 2:
            item_ns.abort(400, "Users may only post up to two items per day.")

        # Create and save the new item
        new_item = Item(
            title=title,
            description=description,
            category=category,
            price=price,
            owner=owner
        )

        db.session.add(new_item)
        db.session.commit()

        return {
            "message": "Item created successfully",
            "item": {
                "id": new_item.id,#the id is generated by the database, as per directions.
                "title": new_item.title,
                "description": new_item.description,
                "category": new_item.category,
                "price": new_item.price,
                "owner": new_item.owner,
                "created_at": new_item.created_at.isoformat()
            } # Return the created item details in the response, only for the swagger(i think)
        }, 201
    



search_parser = item_ns.parser()

search_parser.add_argument(
    "category",
    type=str,
    required=True,
    location="args",
    help="Category to search for"
)

@item_ns.route("/search")
class SearchItems(Resource):

    @item_ns.expect(search_parser)
    @item_ns.marshal_list_with(item_model_with_id) #returns the same model as item_model, since we are returning the same fields as the item_model, but we can create a new model if we want to return different fields.
    @item_ns.response(200, "Items found")
    @item_ns.response(400, "Category is required")
    def get(self):

        args = search_parser.parse_args()

        category = args["category"].strip().lower()

        items = Item.query.filter_by(category=category).all()

        return items
    #Important note, if there is no maches, it returns '[]', which indicates that there are no items in that category.